# Generated by Django 4.2.14 on 2024-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('RegID', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=25)),
                ('Purpose', models.CharField(max_length=155)),
            ],
        ),
    ]
