# Generated by Django 4.2.14 on 2024-07-23 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetailsmodel',
            name='Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
