# Generated by Django 4.2.14 on 2024-07-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_formdetailsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetailsmodel',
            name='Type',
            field=models.CharField(choices=[['Staff', 'Staff'], ['Student', 'Student']], default='Staff', max_length=15),
            preserve_default=False,
        ),
    ]
