# Generated by Django 4.2.14 on 2024-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formdetailsmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetailsmodel',
            name='Subject',
            field=models.CharField(default='Subject', max_length=155),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formdetailsmodel',
            name='Purpose',
            field=models.CharField(max_length=255),
        ),
    ]
