# Generated by Django 4.2.14 on 2024-07-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_formdetailsmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetailsmodel',
            name='Coordinator_Approval',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetailsmodel',
            name='Dean_Approval',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetailsmodel',
            name='DeputyDean_Approval',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetailsmodel',
            name='ProVC_Approval',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
