# Generated by Django 4.2.15 on 2024-09-28 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_formdetailsmodel_coordinator_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetailsmodel',
            name='AdditionalDocuments',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdetailsmodel',
            name='EventDate_From',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdetailsmodel',
            name='EventDate_To',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdetailsmodel',
            name='LetterThrough',
            field=models.CharField(default='', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdetailsmodel',
            name='LetterTo',
            field=models.CharField(default='', max_length=65),
            preserve_default=False,
        ),
    ]
